# Generated by Django 4.1.7 on 2023-02-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('second_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('emp_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_list.department')),
                ('emp_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_list.title')),
            ],
        ),
    ]
