# Generated by Django 4.1.7 on 2023-02-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_list', '0002_employee_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.CharField(default='none', max_length=40),
        ),
    ]
